OAM-200: Delele orders
OpenLMIS/openlmis-fulfillment pull request #32
Opened 2024-06-17 11:46 UTC by tsznaj

(cherry picked from commit fd63632492b7dbf315bcf6be89c5b52f822b5306)

2024-06-17 11:59 UTC, pwargulak requested changes
I'm missing CREATING-status check for Order deletion.

@sradziszewski do permissions have migration scripts?

2024-06-17 11:59 UTC, pwargulak commented on src/main/java/org/openlmis/fulfillment/web/OrderController.java
> +      XLOGGER.info("Nothing to delete");
Missing an early exit?

2024-06-17 14:36 UTC, sradziszewski commented
> I'm missing CREATING-status check for Order deletion.
> 
> @sradziszewski do permissions have migration scripts?

Yes, if we want to check it this way, we need to add the ORDER_DELETE right using migration.

2024-06-17 14:37 UTC, sradziszewski reviewed
Add migration with new right insertion.

2024-06-17 15:30 UTC, tsznaj commented
Added rights here: https://github.com/OpenLMIS/openlmis-referencedata/pull/105

2024-06-17 16:45 UTC, pwargulak requested changes
Still can't see how the 3rd AC is solved:

> Orders must have the status CREATING  in order to be eligible for deletion. Other statuses will not be accepted.

2024-06-18 08:44 UTC, sradziszewski approved these changes

2024-06-18 08:44 UTC, sradziszewski commented on src/integration-test/java/org/openlmis/fulfillment/web/OrderControllerIntegrationTest.java
> +
Remove redundant empty line.

2024-06-18 08:48 UTC, tsznaj commented on src/integration-test/java/org/openlmis/fulfillment/web/OrderControllerIntegrationTest.java
> +
funny comment after so many crazy commits :D

2024-06-18 10:27 UTC, merged